---
#==============================================================================+
# Description : Install IPA packages
#
# Supported OS: EL7 & EL6
#
# Created by: Panxatony
#
#==============================================================================+

- name: remove chronyd
  yum: name="{{item}}" state=absent
  with_items:
     - "chronyd"
  tags:
    - freeipa-client

- name: install IPA software group
  yum: name="{{item}}" state=present
  with_items:
     - "ntp"
     - "sssd"
     - "sssd-client"
     - "sssd-proxy"
     - "sssd-ipa"
     - "authconfig"
     - "ipa-client"
     - "oddjob-mkhomedir"
  tags:
    - freeipa-client

