---
#==============================================================================+
# Description : Execute tasks to add system to FreeIPA directory server
#
# Supported OS: EL7 & EL6
#
# Created by: Panxatony
#
#==============================================================================+


# start IPA client rollout
- include: set-resolv.conf.yml tags=freeipa-client
- include: install-ipa-client.yml tags=freeipa-client
- include: client-enroll-ipa.yml tags=freeipa-client
- include: add-hostgroup.yml tags=freeipa-client
  when: freeipa_add_hostgroup == true