---
#==============================================================================+
# Description : Set IPA Server as DNS server
#
# Supported OS: EL7 & EL6
#
# Created by: Panxatony
#
#==============================================================================+

- name: Creates the /etc/resolv.conf file 
  template: src=etc-resolv.conf.j2 dest=/etc/resolv.conf
